version: '3.8'

services:
  tests:
    build: .
    container_name: api_test_framework
    volumes:
      - ./allure-results:/app/allure-results
      - .:/app
    environment:
      - CLIENT=${CLIENT}
      - ALLURE_RESULTS_DIRECTORY=/app/allure-results
    command: pytest tests/ --order-dependencies --alluredir=/app/allure-results -v

  allure:
    image: frankescobar/allure-docker-service:latest
    container_name: allure-report-service
    ports:
      - "4040:4040"
      - "5050:5050"
    volumes:
      - ./allure-results:/app/allure-results
    environment:
      - CHECK_RESULTS_EVERY_SECONDS=5
      - KEEP_HISTORY=1
      - KEEP_HISTORY_LATEST=20
    depends_on:
      - tests
