[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    -v
    --tb=short
    --strict-markers
    --alluredir=./allure-results
    --order-dependencies

markers =
    order: маркер порядка выполнения тестов (pytest-order)
    smoke: smoke тесты (критический путь)
    regression: регрессионные тесты
    integration: интеграционные тесты

filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning

# Настройки Allure
allure_report_dir = ./allure-results
