[pytest]
addopts = -v --tb=short --strict-markers
markers =
    order: маркер порядка выполнения тестов

filterwarnings =
    ignore::DeprecationWarning

# Настройки Allure
allure_report_dir = ./allure-results
